CREATE DATABASE TAKEPIZZA
GO

USE TAKEPIZZA
GO

CREATE TABLE TB_USUARIO(
	ID_USUARIO		 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME			 VARCHAR(100)	 NOT NULL,
	ST_TELEFONE		 VARCHAR(20)	 NOT NULL,
	ST_EMAIL		 VARCHAR(100)	 NOT NULL,
	ST_CPF			 VARCHAR(20)	 NOT NULL,
	ST_SENHA		 VARCHAR(20)	 NOT NULL,
	DT_ADMINISTRADOR BIT DEFAULT 0	 NOT NULL,
	ST_CEP			 VARCHAR(15),
	ST_RUA			 VARCHAR(200),
	ST_NUMEROLOCAL	 VARCHAR(50)	
);

CREATE TABLE TB_PRODUTO(
	ID_PRODUTO		 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME			 VARCHAR(50),
	ST_TIPO			 VARCHAR(30)
)

INSERT INTO TB_PRODUTO VALUES
('Strogonoff', 'Especial'),
('Calabresa', 'Tradicional'),
('Camarão', 'Especial'),
('Chocolate', 'Doce');

CREATE TABLE TB_TAMANHO(
	ID_TAMANHO	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME		 VARCHAR(15)
)

insert into TB_TAMANHO values
('PEQUENO'),
('MÉDIO'),
('GRANDE'),
('GIGANTE');

CREATE TABLE TB_PRODUTO_X_TAMANHO(
	ID_PRODXTAMANHO	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	DT_PRECO_TOTAL	 DECIMAL(8,2),
	ID_PRODUTO		 INTEGER REFERENCES TB_PRODUTO,
	ID_TAMANHO		 INTEGER REFERENCES TB_TAMANHO
)

DELETE FROM TB_PRODUTO_X_TAMANHO;

DECLARE @ID_PRODUTO int, @ROW_INDEX decimal(15,2) = 0;

-- Cursor para percorrer os registros
DECLARE cursor1 CURSOR FOR
SELECT ID_PRODUTO FROM TB_PRODUTO
 
--Abrindo Cursor
OPEN cursor1
 
-- Lendo a próxima linha
FETCH NEXT FROM cursor1 INTO @ID_PRODUTO
 
-- Percorrendo linhas do cursor (enquanto houverem)
WHILE @@FETCH_STATUS = 0
BEGIN
	
	-- Executando as rotinas desejadas manipulando o registro
	insert into TB_PRODUTO_X_TAMANHO (DT_PRECO_TOTAL, ID_PRODUTO, ID_TAMANHO) values (cast(11.0 + @ROW_INDEX as decimal(15,2)), @ID_PRODUTO, 1);
	insert into TB_PRODUTO_X_TAMANHO (DT_PRECO_TOTAL, ID_PRODUTO, ID_TAMANHO) values (cast(12.0 + @ROW_INDEX as decimal(15,2)), @ID_PRODUTO, 2);
	insert into TB_PRODUTO_X_TAMANHO (DT_PRECO_TOTAL, ID_PRODUTO, ID_TAMANHO) values (cast(13.0 + @ROW_INDEX as decimal(15,2)), @ID_PRODUTO, 3);
	insert into TB_PRODUTO_X_TAMANHO (DT_PRECO_TOTAL, ID_PRODUTO, ID_TAMANHO) values (cast(14.0 + @ROW_INDEX as decimal(15,2)), @ID_PRODUTO, 4);
	SET @ROW_INDEX = @ROW_INDEX + 10.0;

-- Lendo a próxima linha
FETCH NEXT FROM cursor1 INTO @ID_PRODUTO
END
 
-- Fechando Cursor para leitura
CLOSE cursor1
 
-- Finalizado o cursor
DEALLOCATE cursor1

CREATE TABLE TB_PEDIDO(
	ID_PEDIDO	     INTEGER IDENTITY(1,1) PRIMARY KEY,
	DT_DATA		     DATETIME NOT NULL DEFAULT GETDATE(),
	QNT_SABORES	     INTEGER,
	ST_STATUS	     VARCHAR(20),
	ID_USUARIO	     INTEGER REFERENCES TB_USUARIO,
	ST_CEP			 VARCHAR(15),
	ST_RUA			 VARCHAR(200),
	ST_NUMEROLOCAL	 VARCHAR(50)
)

CREATE TABLE TB_ITEM_PEDIDO(
	ID_ITEM				 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ID_PEDIDO			 INTEGER REFERENCES TB_PEDIDO,
	ID_PRODXTAMANHO		 INTEGER REFERENCES TB_PRODUTO_X_TAMANHO,
	PRECO_ITEM			 DECIMAL(8,2)
)

-- SELECT * FROM TB_USUARIO
-- SELECT * FROM TB_PRODUTO
-- SELECT * FROM TB_TAMANHO
-- SELECT * FROM TB_PRODUTO_X_TAMANHO
-- SELECT * FROM TB_PEDIDO
-- SELECT * FROM TB_ITEM_PEDIDO