CREATE DATABASE TAKEPIZZA;
USE TAKEPIZZA;

CREATE TABLE TB_USUARIO(
	ID_USUARIO		 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME			 VARCHAR(100)	 NOT NULL,
	ST_TELEFONE		 VARCHAR(20)	 NOT NULL,
	ST_EMAIL		 VARCHAR(100)	 NOT NULL,
	ST_CPF			 VARCHAR(20)	 NOT NULL,
	ST_SENHA		 VARCHAR(20)	 NOT NULL,
	DT_ADMINISTRADOR BIT DEFAULT 0	 NOT NULL
);

CREATE TABLE TB_PRODUTO(
	ID_PRODUTO		 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME			 VARCHAR(50),
	ST_TIPO			 VARCHAR(30),
	DT_PRECO		 DECIMAL(2,2)
)

CREATE TABLE TB_TAMANHO(
	ID_TAMANHO	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME		 VARCHAR(15)
)

CREATE TABLE TB_PRODUTO_X_TAMANHO(
	ID_PRODXTAMANHO	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	DT_PRECO_TOTAL	 DECIMAL(8,2),
	ID_PRODUTO		 INTEGER REFERENCES TB_PRODUTO,
	ID_TAMANHO		 INTEGER REFERENCES TB_TAMANHO
)

CREATE TABLE TB_PEDIDO(
	ID_PEDIDO	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	DT_DATA		 DATE,
	ST_TAMANHO	 VARCHAR(50),
	QNT_SABORES	 INTEGER,
	ST_STATUS	 VARCHAR(20),
	ID_USUARIO	 INTEGER REFERENCES TB_USUARIO,
	ST_CEP			 VARCHAR(9)		 NOT NULL,
	ST_RUA			 VARCHAR(100)	 NOT NULL,
	ST_NUMEROLOCAL	 INTEGER		 NOT NULL
)

CREATE TABLE TB_ITEM_PEDIDO(
	ID_ITEM				 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ID_PEDIDO			 INTEGER REFERENCES TB_PEDIDO,
	ID_PRODXTAMANHO		 INTEGER REFERENCES TB_PRODUTO_X_TAMANHO,
	PRECO_ITEM			 DECIMAL(8,2)
)

-- SELECT * FROM TB_USUARIO
-- SELECT * FROM TB_PRODUTO
-- SELECT * FROM TB_TAMANHO
-- SELECT * FROM TB_PRODUTO_X_TAMANHO
-- SELECT * FROM TB_PEDIDO
-- SELECT * FROM TB_ITEM_PEDIDO