CREATE DATABASE TAKEPIZZA;
USE TAKEPIZZA;

CREATE TABLE TB_USUARIO(
	ID_USUARIO		 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME			 VARCHAR(50)	 NOT NULL,
	ST_TELEFONE		 VARCHAR(20)	 NOT NULL,
	ST_EMAIL		 VARCHAR(100)	 NOT NULL,
	ST_CPF			 VARCHAR(11)	 NOT NULL,
	ST_SENHA		 VARCHAR(15)	 NOT NULL,
	ST_CEP			 VARCHAR(9)		 NOT NULL,
	ST_RUA			 VARCHAR(100)	 NOT NULL,
	ST_NUMEROLOCAL	 INTEGER		 NOT NULL
);

CREATE TABLE TB_PRODUTO(
	ID_PRODUTO	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_NOME		 VARCHAR(50),
	DT_PRECO	 DECIMAL(2,2)
)

CREATE TABLE TB_PIZZA(
	ID_PIZZA	 INTEGER IDENTITY(1,1) PRIMARY KEY,
	ST_TAMANHO	 VARCHAR(50),
	QNT_SABORES	 INTEGER,
	DT_PRECO	 DECIMAL(2,2)
)

CREATE TABLE TB_PEDIDO(
	ID_PRODUTO		 INTEGER REFERENCES TB_PRODUTO,
	ID_PIZZA		 INTEGER REFERENCES TB_PIZZA,
	DATA			 DATE,
	DT_VALOR_TOTAL	 DECIMAL(4,2),
	ID_USUARIO		 INTEGER REFERENCES TB_USUARIO,
	ST_STATUS		 VARCHAR(50)
)
